network:
    ethernets:
        enp0s31f6:
            addresses:
                - 192.168.2.134/24
            routes:
                - to: default
                  via: 192.168.2.1
            nameservers:
                addresses: [8.8.8.8, 8.8.4.4]
    version: 2
    renderer: networkd
