#!/bin/bash

# Copyright (c) 2024-2024 Burak Günaydin
# All Rights Reserved
#
# This software is the confidential and proprietary information of
# Burak Günaydin. You may not use, modify, or distribute this
# software (unless you have the permission of the copyright holder)
# except in accordance with the terms of any applicable license agreement.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#########################################################
#################### START CMD PARSE ####################
#########################################################

# Check if there are any arguments
if [ "$#" -gt 0 ]; then
    echo
    echo "This script does not accept any arguments. Proceeding ..."
    echo
fi

#########################################################
##################### END CMD PARSE #####################
#########################################################

#########################################################
##################### SCRIPT START ######################
#########################################################

# This script sets an environment variable to prevent Python from writing .pyc files
# and then executes the main script for the HomePie CLI.

# Set the PYTHONDONTWRITEBYTECODE environment variable to 1
# This ensures that Python does not write .pyc files, which can be useful for development
# and debugging purposes as it prevents the creation of bytecode files.
export PYTHONDONTWRITEBYTECODE=1

# Execute the main script for the HomePie CLI
# This script is located at /usr/local/src/homepie/cli/main
# and is the entry point for the HomePie command-line interface.
# Ensure that the main script has execute permissions.
/usr/local/src/homepie/cli/main