#!/bin/bash

# Copyright (c) 2024-2025 Burak Günaydin
# All Rights Reserved
#
# This software is the confidential and proprietary information of
# Burak Günaydin. You may not use, modify, or distribute this
# software (unless you have the permission of the copyright holder)
# except in accordance with the terms of any applicable license agreement.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Set the PYTHONDONTWRITEBYTECODE environment variable to 1
# This ensures that Python does not write .pyc files, which can be useful for development
# and debugging purposes as it prevents the creation of bytecode files.
export PYTHONDONTWRITEBYTECODE=1

# Execute the main script of the homepie CLI tool with all passed arguments
# "$@" ensures that all arguments passed to this script are forwarded to the main script.
# /usr/local/src/homepie/cli/main is the path to the main script of the homepie CLI tool.
# This allows the user to run the homepie CLI tool with the same arguments as they would
# when running the main script directly.
/usr/local/src/homepie/cli/main "$@"