#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Set the PYTHONDONTWRITEBYTECODE environment variable to 1
# This ensures that Python does not write .pyc files, which can be useful for development
# and debugging purposes as it prevents the creation of bytecode files.
export PYTHONDONTWRITEBYTECODE=1

# TODO: Decouple the path to .env
. /usr/local/src/homepie/homepie-venv/bin/activate

# Execute the main script of the homepie CLI tool with all passed arguments
# "$@" ensures that all arguments passed to this script are forwarded to the main script.
# /usr/local/src/homepie/cli/main is the path to the main script of the homepie CLI tool.
# This allows the user to run the homepie CLI tool with the same arguments as they would
# when running the main script directly.
/usr/local/src/homepie/cli/main "$@"