#!/bin/bash

# Copyright (c) 2024-2024 Burak Günaydin
# All Rights Reserved
#
# This software is the confidential and proprietary information of
# Burak Günaydin. You may not use, modify, or distribute this
# software (unless you have the permission of the copyright holder)
# except in accordance with the terms of any applicable license agreement.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#########################################################
#################### START CMD PARSE ####################
#########################################################

# Check if there are any arguments
if [ "$#" -gt 0 ]; then
    echo
    echo "This script does not accept any arguments. Proceeding ..."
    echo
fi

#########################################################
##################### END CMD PARSE #####################
#########################################################

#########################################################
##################### SCRIPT START ######################
#########################################################

# Asking for sudo permissions before script executes any further and surpresses usage information
sudo 2>/dev/null

# Install ddclient package using apt-get
sudo apt-get install -y ddclient

# This script configures ddclient, a client for updating dynamic DNS entries.
# It writes the configuration to /etc/ddclient.conf using sudo privileges.
# The configuration specifies:
# - The method to obtain the external IP address (use=web, web=dynamicdns.park-your-domain.com/getip)
# - The protocol to use (protocol=namecheap)
# - The server to connect to (server=dynamicdns.park-your-domain.com)
# - The login credentials (login=<yourdomain.com>, password=<yourpassword>)
# - The hostname to update (www)
sudo echo "use=web, web=dynamicdns.park-your-domain.com/getip
protocol=namecheap
server=dynamicdns.park-your-domain.com
login=<yourdomain.com>
password=<yourpassword>
www" > /etc/ddclient.conf

# # Open the ddclient configuration file in vim for manual editing
sudo vim /etc/ddclient.conf

# Run ddclient in the foreground for debugging purposes
# Options:
# -daemon=0: Do not run as a daemon
# -debug: Enable debugging output
# -verbose: Enable verbose output
# -noquiet: Do not suppress non-error messages
sudo ddclient -daemon=0 -debug -verbose -noquiet

# Enable ddclient to start on boot
sudo systemctl enable ddclient

# Start the ddclient service
sudo systemctl start ddclient