#!/bin/bash

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

#########################################################
#################### START CMD PARSE ####################
#########################################################

# Check if there are any arguments
if [ "$#" -gt 0 ]; then
    echo
    echo "Hint: This script does not accept any arguments. Proceeding anyways ..."
    echo
fi

#########################################################
##################### END CMD PARSE #####################
#########################################################

#########################################################
##################### SCRIPT START ######################
#########################################################

# Asking for sudo permissions before script executes any further and surpresses usage information
sudo 2>/dev/null

# Install Certbot and the Certbot Nginx plugin using apt-get
sudo apt-get install -y certbot python3-certbot-nginx

# Obtain SSL certificates for homepie.net and www.homepie.net using Certbot
sudo certbot -d homepie.net -d www.homepie.net

# Check the status of the Certbot timer to ensure it is running
sudo systemctl status certbot.timer

# Perform a dry run of the certificate renewal process to verify it works correctly
sudo certbot renew --dry-run

# Stop and disable the Nginx service
sudo systemctl stop nginx
sudo systemctl disable nginx