#!/bin/bash

# Copyright (c) 2024-2025 Burak Günaydin
# All Rights Reserved
#
# This software is the confidential and proprietary information of
# Burak Günaydin. You may not use, modify, or distribute this
# software (unless you have the permission of the copyright holder)
# except in accordance with the terms of any applicable license agreement.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#########################################################
#################### START CMD PARSE ####################
#########################################################

# Check if there are any arguments
if [ "$#" -gt 0 ]; then
    echo
    echo "Hint: This script does not accept any arguments. Proceeding anyways ..."
    echo
fi

#########################################################
##################### END CMD PARSE #####################
#########################################################

#########################################################
##################### SCRIPT START ######################
#########################################################

# Asking for sudo permissions before script executes any further and surpresses usage information
sudo 2>/dev/null

# Install Certbot and the Certbot Nginx plugin using apt-get
sudo apt-get install -y certbot python3-certbot-nginx

# Obtain SSL certificates for homepie.net and www.homepie.net using Certbot
sudo certbot -d homepie.net -d www.homepie.net

# Check the status of the Certbot timer to ensure it is running
sudo systemctl status certbot.timer

# Perform a dry run of the certificate renewal process to verify it works correctly
sudo certbot renew --dry-run

# Stop and disable the Nginx service
sudo systemctl stop nginx
sudo systemctl disable nginx