#!/bin/bash

# Copyright (c) 2024-2024 Burak Günaydin
# All Rights Reserved
#
# This software is the confidential and proprietary information of
# Burak Günaydin. You may not use, modify, or distribute this
# software (unless you have the permission of the copyright holder)
# except in accordance with the terms of any applicable license agreement.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#########################################################
#################### START CMD PARSE ####################
#########################################################

# Check if there are any arguments
if [ "$#" -gt 0 ]; then
    echo
    echo "Hint: This script does not accept any arguments. Proceeding anyways ..."
    echo
fi

#########################################################
##################### END CMD PARSE #####################
#########################################################

#########################################################
##################### SCRIPT START ######################
#########################################################

# This script copies the 'proxy' executable from the source directory to the '/usr/local/bin' directory.
# The copied file is renamed to 'hp' in the destination directory.
# This allows the 'hp' command to be used system-wide as it is placed in a directory that is typically included in the system's PATH.
sudo cp /usr/local/src/homepie/cli/proxy /usr/local/bin/hp