#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# System imports
import os
import sys

'''
Add the parent directory of 'src' to the system path.
This allows the script to import modules from the 'src' directory.
Specifically, it inserts the absolute path of the 'src' directory
at the beginning of the system path list (sys.path).
This is useful when the script is executed from a different directory
and needs to access modules located in 'src'.
'''
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# From own imports
from src.BaseCLI import BaseCLI

class ImportSchema(BaseCLI):
    def meta(self):
        return {
            'name': 'import-schema',
            'shorthand': 'is',
            'help': 'List the import schemas',
            'commands': [
                {
                    'name': 'all',
                    'shorthand': 'a',
                    'help': 'List all import schema',
                },
                {
                    'name': 'go',
                    'shorthand': 'g',
                    'help': 'List the go import schema',
                },
                {
                    'name': 'python',
                    'shorthand': 'py',
                    'help': 'List the python import schema',
                },
                {
                    'name': 'typescript',
                    'shorthand': 'ts',
                    'help': 'List the typescript import schema',
                }
            ],
            'flags': [
                {
                    'long': 'no-copy',
                    'short': 'nc',
                    'help': 'Stop copying the import schema',
                    'required': False,
                },
                {
                    'long': 'no-print',
                    'short': 'nv',
                    'help': 'Stop printing the import schema',
                    'required': False
                },
                {
                    'long': 'no-verbose',
                    'short': 'nv',
                    'help': 'Stop printing verbose output',
                    'required': False
                }
            ]
        }

    def execute(self):
        pass

if __name__ == '__main__':
    ImportSchema()