#!/usr/bin/env python3.11

# Copyright (c) 2024-2024 Burak Günaydin
# All Rights Reserved
#
# This software is the confidential and proprietary information of
# Burak Günaydin. You may not use, modify, or distribute this
# software (unless you have the permission of the copyright holder)
# except in accordance with the terms of any applicable license agreement.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# System imports
import json
import os
import sys

'''
Add the parent directory of 'src' to the system path.
This allows the script to import modules from the 'src' directory.
Specifically, it inserts the absolute path of the 'src' directory
at the beginning of the system path list (sys.path).
This is useful when the script is executed from a different directory
and needs to access modules located in 'src'.
'''
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# From own imports
from src.BaseCLI import BaseCLI

class Install(BaseCLI):
    def meta(self):
        return {
            'name': 'install',
            'shorthand': 'il',
            'help': 'Execute global installation scripts',
            'commands': [
                {
                    'name': 'all',
                    'shorthand': 'a',
                    'help': 'Execute all global scripts',
                },
                {
                    'name': 'cli',
                    'shorthand': 'ci',
                    'help': 'Execute the CLI installation script only'
                }
            ],
            'flags': [
                {
                    'short': 'e',
                    'long': 'env',
                    'help': 'Set the environment for the installation script',
                    'options': ['dev', 'prod'],
                    'required': True
                },
            ],
        }

    def execute(self):
        '''
        This script copies the 'proxy' executable from the source directory to the '/usr/local/bin' directory.
        The copied file is renamed to 'hp' in the destination directory.
        This allows the 'hp' command to be used system-wide as it is placed in a directory that is typically included in the system's PATH.
        '''
        if self.get_command() == 'all':
            self.shell('sh /usr/local/src/homepie/cli/build-scripts/install-cli', sudo=True)
        elif self.get_command() == 'cli':
            self.shell('sh /usr/local/src/homepie/cli/build-scripts/install-cli', sudo=True)

if __name__ == '__main__':
    Install()