#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# System imports
import json
import os
import sys

'''
Add the parent directory of 'src' to the system path.
This allows the script to import modules from the 'src' directory.
Specifically, it inserts the absolute path of the 'src' directory
at the beginning of the system path list (sys.path).
This is useful when the script is executed from a different directory
and needs to access modules located in 'src'.
'''
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# From own imports
from src.BaseCLI import BaseCLI

class Install(BaseCLI):
    def meta(self):
        return {
            'name': 'install',
            'shorthand': 'il',
            'help': 'Execute global installation scripts',
            'commands': [
                {
                    'name': 'all',
                    'shorthand': 'a',
                    'help': 'Execute all global scripts',
                },
                {
                    'name': 'cli',
                    'shorthand': 'ci',
                    'help': 'Execute the CLI installation script only'
                }
            ],
            'flags': [
                {
                    'short': 'e',
                    'long': 'env',
                    'help': 'Set the environment for the installation script',
                    'options': ['dev', 'prod'],
                    'required': True
                },
            ],
        }

    def execute(self):
        '''
        This script copies the 'proxy' executable from the source directory to the '/usr/local/bin' directory.
        The copied file is renamed to 'hp' in the destination directory.
        This allows the 'hp' command to be used system-wide as it is placed in a directory that is typically included in the system's PATH.
        '''
        if self.get_command() == 'all':
            self.shell('sh /usr/local/src/homepie/cli/build-scripts/install-cli', sudo=True)
        elif self.get_command() == 'cli':
            self.shell('sh /usr/local/src/homepie/cli/build-scripts/install-cli', sudo=True)

if __name__ == '__main__':
    Install()