#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# System imports
import os

# From package imports
from teatype.cli import BaseCLI
from teatype.logging import err

class MakeExecutable(BaseCLI):
    def meta(self):
        return {
            'name': 'make-executable',
            'shorthand': 'me',
            'help': 'Make a file executable by setting the executable bit, allowing it to be run as a program, omitting the interpreter',
            'arguments': [
                {
                    'name': 'filename',
                    'help': 'The name of the file (or directory including files) to make executable',
                    'required': True
                }
            ],
            'flags': [
                {
                    'short': 'ng',
                    'long': 'no-git',
                    'help': ['Disables adding the file to the git index and setting the executable bit',
                             '(This flag is not recommended for version control)'],
                    'required': False
                },
            ]
        }

    def make_file_executable(self, file:str, git_support:bool):
        """
        Make a single file executable and optionally add it to the git index.

        :param file: The file to make executable.
        :param git_support: Boolean indicating whether to add the file to the git index.
        """
        # Change the file permissions to make it executable by all users.
        self.shell(f'chmod a+x {file}', sudo=True)
        # Set the file permissions to 755 (rwxr-xr-x).
        self.shell(f'chmod 755 {file}', sudo=True)
        if git_support:
            # Add the file to the git index.
            self.shell(f'git add {file}')
            # Update the git index to mark the file as executable.
            self.shell(f'git update-index --chmod=+x {file}')

    def execute(self):
        """
        Execute the command to make the specified file or directory executable.
        """
        # Check if the --no-git flag is set.
        git_support = not self.get_flag('--no-git')
        # Get the filename argument from the command line.
        filename = self.get_argument('filename')
        
        # Check if the provided filename is a directory or a file.
        if os.path.isdir(filename):
            # Walk through the directory and make all files executable.
            for root, _, files in os.walk(filename):
                for file in files:
                    # Make each file in the directory executable.
                    self.make_file_executable(os.path.join(root, file), git_support)
        elif os.path.isfile(filename):
            # Make the single specified file executable.
            self.make_file_executable(filename, git_support)
        else:
            # If the path is neither a file nor a directory, raise an error.
            err(f'The path "{filename}" is neither a file nor a directory.', exit=True, traceback=True)
    
if __name__ == '__main__':
    MakeExecutable()