#!/usr/bin/env python3.11

# Copyright (c) 2024-2024 Burak Günaydin
# All Rights Reserved
#
# This software is the confidential and proprietary information of
# Burak Günaydin. You may not use, modify, or distribute this
# software (unless you have the permission of the copyright holder)
# except in accordance with the terms of any applicable license agreement.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# System imports
import json
import os
import sys

# Add the parent directory of 'src' to the system path.
# This allows the script to import modules from the 'src' directory.
# Specifically, it inserts the absolute path of the 'src' directory
# at the beginning of the system path list (sys.path).
# This is useful when the script is executed from a different directory
# and needs to access modules located in 'src'.
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# From own imports
from src.BaseCLI import BaseCLI

# This is a test if double chatter occurs at 8Hz, but that doesnt seems to be the case which is really fucking awesome because this means I can type as fast as I can

class ResetFirewall(BaseCLI):
    def meta(self):
        return {
            'name': 'reset-firewall',
            'shorthand': 'rf',
            'help': 'Resets the firewall rules to the default settings.'
        }

    def execute(self):
        # Disable ufw to preserve existing ssh connection
        self.shell('ufw disable', sudo=True)

        # Resetting firewall rules
        self.shell('ufw reset -y', sudo=True)

        # Enable ufw
        self.shell('ufw enable', sudo=True)

        # Allow SSH (port 22)
        self.shell('ufw allow 22/tcp', sudo=True)

        # Allow HTTP (port 80)
        self.shell('ufw allow 80/tcp', sudo=True)
        self.shell('ufw allow out 80/tcp', sudo=True)

        # Allow HTTPS (port 443)
        self.shell('ufw allow 443/tcp', sudo=True)
        self.shell('ufw allow out 443/tcp', sudo=True)

        # Deny all other incoming connections
        self.shell('ufw default deny incoming', sudo=True)

if __name__ == '__main__':
    reset_firewall = ResetFirewall()