#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# From package imports
from teatype.cli import BaseCLI

# This is a test if double chatter occurs at 8Hz, but that doesnt seems to be the case which is really fucking awesome because this means I can type as fast as I can

class ResetFirewall(BaseCLI):
    def meta(self):
        return {
            'name': 'reset-firewall',
            'shorthand': 'rf',
            'help': 'Resets the firewall rules to the custom default settings',
            'flags': [
                {
                    'short': 'd',
                    'long': 'default',
                    'help': 'Reset to system default instead',
                    'required': False
                },
            ],
        }

    def execute(self):
        # Disable ufw to preserve existing ssh connection
        self.shell('ufw disable', sudo=True)

        # Resetting firewall rules
        self.shell('ufw reset -y', sudo=True)

        # Enable ufw
        self.shell('ufw enable', sudo=True)
        
        if not self.get_flag('--default'):
            # Allow SSH (port 22)
            self.shell('ufw allow 22/tcp', sudo=True)

            # Allow HTTP (port 80)
            self.shell('ufw allow 80/tcp', sudo=True)
            self.shell('ufw allow out 80/tcp', sudo=True)

            # Allow HTTPS (port 443)
            self.shell('ufw allow 443/tcp', sudo=True)
            self.shell('ufw allow out 443/tcp', sudo=True)

            # Deny all other incoming connections
            self.shell('ufw default deny incoming', sudo=True)

if __name__ == '__main__':
    reset_firewall = ResetFirewall()