#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# From package imports
from teatype.cli import BaseCLI

# TODO: Implement
class Symlink(BaseCLI):
    def meta(self):
        return {
            'name': 'symlink',
            'shorthand': 'sl',
            'help': 'Create a (specific) symlink',
            'commands': [
                {
                    'name': 'teatype',
                    'shorthand': 'a',
                    'help': 'List teatype import schema',
                }
            ],
            'flags': [
                {
                    'long': 'no-copy',
                    'short': 'nc',
                    'help': 'Stop copying the import schema',
                    'required': False
                },
            ]
        }

    def execute(self):
        pass

if __name__ == '__main__':
    Symlink()