#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# From own imports
from teatype.cli import BaseCLI
from teatype.logging import err
        
class System(BaseCLI):
    def meta(self):
        return {
            'name': 'system',
            'shorthand': 'sys',
            'help': 'Useful system command shortcuts',
            'commands': [
                {
                    'name': 'monitor',
                    'shorthand': 'mt',
                    'help': 'Monitor system resources'
                },
                {
                    'name': 'reboot',
                    'shorthand': 'rb',
                    'help': 'Reboot the system'
                },
                {
                    'name': 'shutdown',
                    'shorthand': 'sh',
                    'help': 'Shutdown the system'
                },
                {
                    'name': 'stress',
                    'shorthand': 'st',
                    'help': 'Stress test the system'
                }
            ]
        }
        
        
    def monitor(self):
        self.shell('htop -d 7 -H -t -U')
        
    def reboot(self):
        self.shell('reboot -h now', sudo=True)
        
    def shutdown(self):
        self.shell('shutdown -h now', sudo=True)
        
    def stress(self):
        self.shell('stress --cpu 8 --io 4 --vm 2 --vm-bytes 128M --timeout 10s')

    def execute(self):
        command = self.get_command()
        
        try:
            if (command == 'monitor' or command == 'mt'):
                self.monitor()
            elif command == 'reboot' or command == 'rb':
                self.reboot()
            elif command == 'shutdown' or command == 'sh':
                self.shutdown()
            elif command == 'stress' or command == 'st':
                self.stress()
        except:
            err('An error occurred while executing the command', exit=True, traceback=True)
        
if __name__ == '__main__':
    System()