#!/usr/bin/env python3.11

# Copyright (C) 2024-2025 Burak Günaydin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# From own imports
from teatype.cli import BaseCLI

class Venv(BaseCLI):
    def meta(self):
        return {
            'name': 'venv',
            'shorthand': 'v',
            'help': 'Create a virtual environment',
            'flags': [
                {
                    'long': 'delete',
                    'short': 'd',
                    'help': 'Delete the virtual environment',
                    'required': False
                },
                {
                    'long': 'no-activation',
                    'short': 'na',
                    'help': 'Stop activating the virtual environment',
                    'required': False
                },
                {
                    'long': 'reset',
                    'short': 'r',
                    'help': 'Reset the virtual environment',
                    'required': False
                }
            ]
        }

    def execute(self):
        pass

if __name__ == '__main__':
    Venv()